In [45]:
def get_user_input(game_board,BOARD_SIZE):
    while True:
        vloc_str = input("Please enter vertical position 0-{}: ".format(BOARD_SIZE-1))
        hloc_str = input("Please enter horizontal position 0-{}: ".format(BOARD_SIZE-1))
        
        if vloc_str.isdigit() and hloc_str.isdigit():
            vloc = int(vloc_str)
            hloc = int(hloc_str)

            if vloc < 0 or vloc > BOARD_SIZE-1:
                print("Invalid position, your input is out of range")
                continue
            if hloc < 0 or hloc > BOARD_SIZE-1:
                print("Invalid position, your input is out of range")
                continue
        else:
            continue
        
        if game_board[vloc,hloc] == 0:
            return vloc,hloc
        else:
            print("Position is filled..............Try again")
            continue
        

In [50]:
def check_ans(game_board, BOARD_SIZE, uid, vloc, hloc):
    h_is_pass = True
    for x in range(BOARD_SIZE):
        if game_board[vloc,x] != uid:
            h_is_pass = False
            break
            
    v_is_pass = True
    for y in range(BOARD_SIZE):
        if game_board[y,hloc] != uid:
            v_is_pass = False
            break
     
    d1_is_pass = True
    for z1 in range(BOARD_SIZE):
        if game_board[z1,z1] != uid:
            d1_is_pass = False
            break
            
    d2_is_pass = True        
    for z2 in range(BOARD_SIZE):
        if game_board[z2,BOARD_SIZE-z2-1] != uid:
            d2_is_pass = False
            break
            
    if h_is_pass:
        print("Horizontal WINS")
        
    if v_is_pass:
        print("Vertical WINS")
        
    if d1_is_pass or d2_is_pass:
        print("Diagonal WINS")
        
    if h_is_pass or v_is_pass or d1_is_pass or d2_is_pass:
        return True
    else:
        return False
        


In [55]:
# Set a new game
#MAIN

import numpy as np
BOARD_SIZE = 3
game_board = np.zeros((BOARD_SIZE,BOARD_SIZE))
uid = 0

for i in range (BOARD_SIZE*BOARD_SIZE):
    if uid == 1:
        uid = 2
    else:
        uid = 1
        
    print("User {} ------- User {}".format(uid,uid))
    print(game_board)
    
    vloc, hloc = get_user_input(game_board,BOARD_SIZE)
    
    game_board[vloc,hloc] = uid
    
    isWin = check_ans(game_board,BOARD_SIZE,uid, vloc, hloc)
    
    if isWin:
        print("By User {} in this game".format(uid))
        break
    else:
        print("DRAW game!")
            
print("***** End Game *****")
    


User 1 ------- User 1
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Please enter vertical position 0-2:  0
Please enter horizontal position 0-2:  0


DRAW game!
User 2 ------- User 2
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Please enter vertical position 0-2:  1
Please enter horizontal position 0-2:  0


DRAW game!
User 1 ------- User 1
[[1. 0. 0.]
 [2. 0. 0.]
 [0. 0. 0.]]


Please enter vertical position 0-2:  0
Please enter horizontal position 0-2:  1


DRAW game!
User 2 ------- User 2
[[1. 1. 0.]
 [2. 0. 0.]
 [0. 0. 0.]]


Please enter vertical position 0-2:  1
Please enter horizontal position 0-2:  1


DRAW game!
User 1 ------- User 1
[[1. 1. 0.]
 [2. 2. 0.]
 [0. 0. 0.]]


Please enter vertical position 0-2:  0
Please enter horizontal position 0-2:  2


Horizontal WINS
By User 1 in this game
***** End Game *****
